title: Susan Craigo
logo: "/images/Susan_2017-11-30_10-41-24_721_med.jpg?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  IT Specialist II, Web Development Specialist at University of Tennessee Knoxville - Institute of Agriculture 
  <br><br>
  Student at Austin Peay State University, majoring in Computer Science - Internet & Web Technology 
  <br><br>
  <a href="https://www.linkedin.com/in/susancraigo/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
