title: Susan Craigo
logo: "/images/Susan_2017-11-30_10-41-24_721_med.jpg?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  IT Specialist II, Web Development Specialist at University of Tennessee Knoxville Institute of Agriculture 
  <br><br>
  
  <a href="https://www.linkedin.com/in/susancraigo/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-158514014-1
